# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    if [ -f "Textfile.txt" ]; then
      echo "SUCCESS: Textfile.txt exists."
    else
      echo "ERROR: Textfile.txt does not exist."
      exit 1
    fi
  displayName: 'Check Textfile.txt exists'